#!/bin/sh

pactl set-sink-mute 1 toggle
mute=$(pacmd list-sinks | awk '/muted/ { print $2 }' | head -n $(( 1 + 1 )) | tail -n 1 | sed 's/muted://g; /^$/ d; s/\s*#.*//g')
if [ $mute = "yes" ]; then
  notify-send "MUTED AUDIO"
elif [ $mute = "no" ]; then
  notify-send "UNMUTED AUDIO"
fi
