#!/bin/sh

SINK=$(pactl list short | grep alsa_output.pci-0000_0c_00.4.analog-stereo \
  | sed '/monitor/ d; s,^\([0-9][0-9]*\)[^0-9].*,\1,')
pactl set-sink-mute "$SINK" toggle
mute=$(pacmd list-sinks | awk '/muted/ { print $2 }' | head -n $(( $SINK + 1 )) | tail -n 1 | sed 's/muted://g; /^$/ d; s/\s*#.*//g')
if [ $mute = "yes" ]; then
  notify-send "MUTED AUDIO"
elif [ $mute = "no" ]; then
  notify-send "UNMUTED AUDIO"
fi
